#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sp4war3.Resource", IsApplication=true)]

namespace Sp4war3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int FeedbackWave = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_create = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_content_feedback = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_content_lab = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_content_save = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_content_trophy = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_contactAssistant = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_copy_holo_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_cut_holo_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_menu_innovation = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_menu_paste_holo_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_menu_search_holo_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_menu_voiceGuidedDeposits = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_settings_black_24dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int wave = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int btnBackToHome = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int btnSubmitFeedback = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int innovation_toolbar = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int main_content = 2131165191;
			
			// aapt resource value: 0x7f07000f
			public const int menu_achievements = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int menu_contactAssistant = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int menu_feedback = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int menu_innovations = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int menu_lab = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int menu_preferences = 2131165201;
			
			// aapt resource value: 0x7f07000c
			public const int menu_voiceGuidedDeposits = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int toolbar = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int txtAchievements = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int txtEnterFeedback = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int txtFeedback = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int txtLab = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int txtSettings = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int welcomeText = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Feedback = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Lab = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layoutHome = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Settings = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Toolbar = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int innovations_menus = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int top_menus = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Sp4war3Theme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
